# Generated by Django 5.1.3 on 2024-11-22 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_alter_parent_mother_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='father_contact',
            field=models.CharField(max_length=15),
        ),
    ]
