# Generated by Django 5.1.3 on 2024-11-22 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_alter_parent_mother_occupation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parent',
            old_name='parent_address',
            new_name='present_address',
        ),
    ]
